# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

require 'yaml'

Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu15.04"
  #config.vm.box_url = "https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/15.04/ubuntu-15.04-amd64.box";
  config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "bento/ubuntu-16.04"

  config.vm.hostname = "rails"

  config.vm.network :private_network, ip: '192.168.88.30'

  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.synced_folder "../", "/vagrant", type: "virtualbox",
                          :mount_options => ["dmode=777", "fmode=777"]

  config.vm.synced_folder "ansible", "/vagrant/dev/ansible", type: "virtualbox",
                          :mount_options => ["dmode=755", "fmode=644"]

  config.vm.provider "virtualbox" do |vm|
     vm.memory = "2048"
  end

  config.vm.provision :shell, :path => "ansible.sh"
end
